import { useState } from "react";
import {
  BadgeCheck, CalendarDays, CheckCircle2, ChevronDown, Clock3, EllipsisVertical,
  Filter, MessageSquareText, Plus, UsersRound, Video, XCircle,
} from "lucide-react";

const sessions = [
  { title: "Career Guidance Session", expert: "Dr. Priya Sharma", role: "MBBS Admission Expert", date: "24 May 2025", day: "Saturday", time: "11:00 AM", duration: "60 mins", status: "Upcoming", initials: "PS", action: "Join Session" },
  { title: "University Selection Guidance", expert: "Mr. Arjun Patel", role: "University Counsellor", date: "27 May 2025", day: "Tuesday", time: "04:00 PM", duration: "60 mins", status: "Upcoming", initials: "AP", action: "Join Session" },
  { title: "Profile Evaluation", expert: "Dr. Neha Verma", role: "MBBS Admission Expert", date: "18 May 2025", day: "Sunday", time: "10:30 AM", duration: "45 mins", status: "Completed", initials: "NV", action: "View Summary" },
  { title: "Document Review", expert: "Mr. Rohan Singh", role: "Documentation Expert", date: "12 May 2025", day: "Monday", time: "02:00 PM", duration: "40 mins", status: "Completed", initials: "RS", action: "View Summary" },
  { title: "Visa Guidance Session", expert: "Ms. Anjali Mehta", role: "Visa & Travel Expert", date: "10 May 2025", day: "Saturday", time: "11:00 AM", duration: "60 mins", status: "Cancelled", initials: "AM", action: "Reschedule" },
];

const statusClass = { Upcoming: "bg-violet-50 text-violet-600", Completed: "bg-emerald-50 text-emerald-600", Cancelled: "bg-rose-50 text-rose-600" };
function Stat({ icon: Icon, value, title, subtitle, color }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm shadow-slate-100"><div className="flex items-center gap-4"><span className={`rounded-2xl p-3 ${color}`}><Icon size={22} /></span><div><p className="text-2xl font-extrabold text-slate-900">{value}</p><p className="mt-1 text-xs font-medium text-slate-600">{title}</p><p className="mt-1 text-[11px] text-slate-500">{subtitle}</p></div></div></div>; }

export default function Counselling() {
  const [tab, setTab] = useState("All Sessions");
  const filtered = tab === "All Sessions" ? sessions : sessions.filter((session) => session.status === tab);
  return <div className="mx-auto w-full max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">Counselling Sessions</h1><p className="mt-1 text-sm text-slate-500">Book and manage your expert counselling sessions.</p></div><button className="inline-flex w-fit items-center gap-1.5 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-200"><Plus size={16} /> Book New Session</button></div>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={CalendarDays} value="2" title="Upcoming Sessions" subtitle="Scheduled" color="bg-violet-100 text-violet-600" /><Stat icon={CheckCircle2} value="3" title="Completed Sessions" subtitle="This Month" color="bg-emerald-50 text-emerald-500" /><Stat icon={Clock3} value="1" title="Pending Sessions" subtitle="To Be Rescheduled" color="bg-amber-50 text-amber-500" /><Stat icon={MessageSquareText} value="5" title="Total Sessions" subtitle="All Time" color="bg-sky-50 text-sky-500" /></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-100"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex overflow-x-auto">{["All Sessions", "Upcoming", "Completed", "Cancelled"].map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-3 py-2 text-sm font-semibold transition ${tab === item ? "border-indigo-600 text-indigo-600" : "border-transparent text-slate-500 hover:text-slate-700"}`}>{item}</button>)}</div><button className="inline-flex w-fit items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600"><Filter size={15} /> Filter <ChevronDown size={14} /></button></div>
      <div>{filtered.map((session) => <article key={`${session.title}-${session.date}`} className="grid gap-4 border-b border-slate-100 p-4 last:border-0 xl:grid-cols-[minmax(280px,1fr)_145px_105px_145px_140px]"><div className="flex items-center gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-slate-200 to-indigo-100 text-sm font-extrabold text-indigo-700">{session.initials}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold text-slate-800">{session.title}</h2><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${statusClass[session.status]}`}>{session.status}</span></div><p className="mt-1 text-xs font-semibold text-slate-600">{session.expert}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500">{session.role} <BadgeCheck size={12} className="text-blue-500" /></p></div></div><div className="flex items-center gap-2 text-xs"><CalendarDays size={16} className="text-slate-500" /><div><p className="font-bold text-slate-700">{session.date}</p><p className="mt-1 text-[11px] text-slate-500">{session.day}</p></div></div><div className="flex items-center gap-2 text-xs"><Clock3 size={16} className="text-slate-500" /><div><p className="font-bold text-slate-700">{session.time}</p><p className="mt-1 text-[11px] text-slate-500">{session.duration}</p></div></div><div className="flex items-center gap-2 text-xs">{session.status === "Cancelled" ? <XCircle size={16} className="text-rose-500" /> : <Video size={16} className="text-slate-500" />}<div><p className={`font-bold ${session.status === "Cancelled" ? "text-rose-600" : "text-slate-700"}`}>{session.status === "Cancelled" ? "Cancelled" : "Online"}</p>{session.status !== "Cancelled" && <p className="mt-1 text-[11px] text-slate-500">Google Meet</p>}</div></div><div className="flex items-center gap-2 xl:justify-end"><button className="rounded-lg border border-violet-300 px-3 py-2 text-xs font-semibold text-violet-600 hover:bg-violet-50">{session.action}</button><button aria-label={`More options for ${session.title}`} className="p-1 text-slate-500"><EllipsisVertical size={18} /></button></div></article>)}</div>
      {filtered.length === 0 && <p className="p-10 text-center text-sm text-slate-500">No sessions in this category.</p>}<div className="m-4 flex flex-col gap-3 rounded-xl bg-violet-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-100 p-2.5 text-violet-600"><UsersRound size={20} /></span><div><p className="text-sm font-bold text-slate-800">Need a personalised counselling session?</p><p className="mt-1 text-xs text-slate-500">Book a one-on-one session with our experts and take the right step towards your dream of studying MBBS abroad.</p></div></div><button className="shrink-0 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-xs font-bold text-white">Book New Session</button></div>
    </section></div>;
}
