import { useState } from "react";
import {
  CheckCircle2, Clock3, Download, EllipsisVertical, FileText,
  Filter, HelpCircle, Plus, ReceiptText, RotateCcw, ShieldCheck, WalletCards, XCircle,
} from "lucide-react";

const payments = [
  { id: "INV-2025-0007", description: "MBBS Program Fee", detail: "Kazan Federal University", amount: "₹ 1,50,000", status: "Paid", date: "20 May 2025", time: "11:30 AM", action: "View Invoice" },
  { id: "INV-2025-0006", description: "Counselling Service Fee", detail: "One-on-one Counselling", amount: "₹ 25,000", status: "Paid", date: "15 May 2025", time: "04:20 PM", action: "View Invoice" },
  { id: "INV-2025-0005", description: "University Application Fee", detail: "Bashkir State Medical University", amount: "₹ 10,000", status: "Pending", date: "—", time: "", action: "Pay Now" },
  { id: "INV-2025-0004", description: "Visa Processing Fee", detail: "Student Visa", amount: "₹ 35,000", status: "Pending", date: "—", time: "", action: "Pay Now" },
  { id: "INV-2025-0003", description: "Document Verification Fee", detail: "Credential Evaluation", amount: "₹ 15,000", status: "Failed", date: "10 May 2025", time: "10:15 AM", action: "Retry Payment" },
  { id: "INV-2025-0002", description: "Initial Registration Fee", detail: "Portal Registration", amount: "₹ 5,000", status: "Paid", date: "05 May 2025", time: "09:40 AM", action: "View Invoice" },
  { id: "INV-2025-0001", description: "Refund - University Application", detail: "Perm State Medical University", amount: "₹ 10,000", status: "Refunded", date: "01 May 2025", time: "02:30 PM", action: "View Invoice" },
];

const statusStyle = { Paid: "bg-emerald-50 text-emerald-600", Pending: "bg-amber-50 text-amber-600", Failed: "bg-rose-50 text-rose-600", Refunded: "bg-sky-50 text-sky-600" };
const StatusIcon = ({ status }) => status === "Paid" ? <CheckCircle2 size={11} /> : status === "Pending" ? <Clock3 size={11} /> : status === "Failed" ? <XCircle size={11} /> : <RotateCcw size={11} />;
function Stat({ icon: Icon, label, value, hint, color }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm shadow-slate-100"><div className="flex items-center gap-4"><span className={`rounded-2xl p-3 ${color}`}><Icon size={21} /></span><div><p className="text-[11px] font-semibold text-slate-600">{label}</p><p className="mt-1 text-2xl font-extrabold text-slate-900">{value}</p><p className="mt-2 text-xs font-medium text-indigo-600">{hint}</p></div></div></div>; }

export default function Payments() {
  const [tab, setTab] = useState("All");
  const filtered = tab === "All" ? payments : payments.filter((payment) => payment.status === tab);
  return <div className="mx-auto w-full max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">Payments</h1><p className="mt-1 text-sm text-slate-500">View your payment history, invoices and make secure payments.</p></div><button className="inline-flex w-fit items-center gap-1.5 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-200"><Plus size={16} /> Make a New Payment</button></div>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={WalletCards} label="Total Paid" value="₹ 2,45,000" hint="All Time" color="bg-violet-100 text-violet-600" /><Stat icon={Clock3} label="Pending Payments" value="₹ 85,000" hint="2 Payments" color="bg-emerald-50 text-emerald-500" /><Stat icon={FileText} label="Total Invoices" value="7" hint="All Time" color="bg-amber-50 text-amber-500" /><Stat icon={ReceiptText} label="Total Refunds" value="₹ 10,000" hint="1 Refund" color="bg-sky-50 text-sky-500" /></section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm shadow-slate-100 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-bold text-slate-900">Payment History</h2><div className="flex gap-2"><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600"><Filter size={14} /> Filter</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600"><Download size={14} /> Download</button></div></div><div className="mt-3 flex overflow-x-auto border-b border-slate-100">{["All", "Paid", "Pending", "Failed", "Refunded"].map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-4 py-2.5 text-sm font-semibold ${tab === item ? "border-indigo-600 text-indigo-600" : "border-transparent text-slate-500 hover:text-slate-700"}`}>{item}</button>)}</div>
      <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] border-separate border-spacing-y-1 text-left"><thead><tr className="bg-indigo-50/70 text-[10px] font-bold uppercase tracking-wide text-slate-500"><th className="rounded-l-lg px-3 py-3">Invoice ID</th><th className="px-3 py-3">Description</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Payment Date</th><th className="rounded-r-lg px-3 py-3">Action</th></tr></thead><tbody>{filtered.map((payment) => <tr key={payment.id} className="text-xs"><td className="border-y border-l border-slate-100 px-3 py-3 font-semibold text-slate-700">{payment.id}</td><td className="border-y border-slate-100 px-3 py-3"><p className="font-bold text-slate-700">{payment.description}</p><p className="mt-1 text-[11px] text-slate-500">{payment.detail}</p></td><td className="border-y border-slate-100 px-3 py-3 font-bold text-slate-700">{payment.amount}</td><td className="border-y border-slate-100 px-3 py-3"><span className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold ${statusStyle[payment.status]}`}><StatusIcon status={payment.status} /> {payment.status}</span></td><td className="border-y border-slate-100 px-3 py-3"><p className="font-medium text-slate-600">{payment.date}</p>{payment.time && <p className="mt-1 text-[11px] text-slate-500">{payment.time}</p>}</td><td className="border-y border-r border-slate-100 px-3 py-3"><div className="flex items-center gap-3"><button className={`rounded-lg px-3 py-1.5 text-[11px] font-semibold ${payment.action === "Pay Now" ? "bg-gradient-to-r from-indigo-600 to-violet-600 text-white" : "border border-violet-300 text-violet-600"}`}>{payment.action}</button><button aria-label={`More options for ${payment.id}`} className="text-slate-500"><EllipsisVertical size={17} /></button></div></td></tr>)}</tbody></table></div><div className="mt-4 flex flex-col gap-3 rounded-xl bg-violet-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-100 p-2.5 text-violet-600"><ShieldCheck size={20} /></span><div><p className="text-sm font-bold text-slate-800">Secure & Hassle-Free Payments</p><p className="mt-1 text-xs text-slate-500">All payments are encrypted and secure. Need help with a payment? Contact our support team.</p></div></div><button className="inline-flex shrink-0 items-center justify-center gap-1.5 rounded-lg border border-violet-300 bg-white px-4 py-2.5 text-xs font-bold text-violet-600"><HelpCircle size={14} /> Payment Help</button></div></section></div>;
}
